pipeline{
    agent any
    stages {
      stage("Repo"){
    checkout scm
    sh 'echo "ayudaaaa"'
       }
      stage('SonarQube analysis') {
    			
				dir("/var/lib/jenkins/workspace/Tingeso") {
					withSonarQubeEnv(installationName: 'sonarqube') { // Will pick the global server connection you have configured
						sh '''gradle sonarqube'''
    					}
				
			}
  		}
              stage("build") {
                   sh 'echo "ayudaaaa2"'
                   sh """ docker build --build-arg JAR_FILE=build/libs/\\*.jar -t demo ."""
                   sh 'echo "ayudaaaa3"'
                  
       
         }
     stage("run") {
                 sh 'docker run -it -p 8081:8081 demo'
                 sh 'echo "ayudaaaa4"'
          }
    }

}